listen_addresses: "0.0.0.0:${MARTIN_PORT}"

cache: disable

postgres:
  connection_string: ${DATABASE_URL}

  functions:
    trails_map_layer:
      schema: 'public'
      function: 'trails_map_layer'
